version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    ui:
        build:
            context: './ui'
        ports:
            - '3000:3000'
        volumes:
            - ./ui/src:/app/src
            - ./ui/.babelrc:/app/.babelrc
            - ./ui/index.template.ejs:/app/index.template.ejs
            - ./ui/webpack.js:/app/webpack.js
            - ./ui/server.js:/app/server.js
    slack:
        depends_on:
            - db
        build:
            context: './slack'
        ports:
            - '8000:8000'
        volumes:
            - ./slack/src:/app/src
            - ./slack/index.js:/app/index.js
